on: 
  push: 
    branches:
     - Develop
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: edit connection string
      uses: benday-inc/edit-dbconnstr-in-appsettings@main
      with:
        pathtosettingsfile: './Pizzaria_back/Pizzaria_back/appsettings.json'
        name: "DB_MySQL"
        connectionstring: ${{ secrets.BANCO_HOST }};${{ secrets.BANCO_DATABASE }};${{ secrets.BANCO_USER }};${{ secrets.BANCO_SENHA }}
    - name: Restore dependencies
      run: dotnet restore ./Pizzaria_back/Pizzaria_back.sln
    - name: Build
      run: dotnet build ./Pizzaria_back/Pizzaria_back.sln -c Release 
    - name: Test
      run: dotnet test ./Pizzaria_back/Pizzaria_back.sln -c Release
    - name: Publish
      run: dotnet publish ./Pizzaria_back/Pizzaria_back.sln -c Release     
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /wwwroot/apidev/
        local-dir: ./Pizzaria_back/Pizzaria_back/bin/Release/net6.0/publish/
        protocol: ftp 
