on: 
  push: 
    branches:
     - Develop
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Pizzaria_back/Pizzaria_back.sln
    - name: Build
      run: dotnet build ./Pizzaria_back/Pizzaria_back/Pizzaria_back.csproj -c Development 
    - name: Test
      run: dotnet test ./Pizzaria_back/Pizzaria.Test/Pizzaria.Test.csproj -c Development
    - name: Publish
      run: dotnet publish ./Pizzaria_back/Pizzaria_back/Pizzaria_back.csproj -c Development     
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /wwwroot/apidev/
        local-dir: ./Pizzaria_back/Pizzaria_back/bin/Development/net6.0/publish/
        protocol: ftp 
        dangerous-clean-slate: true
